### ISSUE TITLE
Migrate testnet node 2 to new vm

### ISSUE THREAD

**Issue by hochiw** [oursky/likecoin-chain#162] opened 2022-03-29 04:53 UTC
- Should follow https://github.com/oursky/likecoin.oursky.dev/tree/master/node-vm-testnet-chima
- Add new entry to the repo
- Add firewall settings to chima README

**Comment by mitchellchou** [comment] 2022-03-29 06:35
duplicate of oursky/likecoin-chain#154

**Comment by rickmak** [comment] 2022-03-30 07:56
@Rico-Wong please also update the https://github.com/oursky/likecoin.oursky.dev/tree/master/likecoin-public-testnet-4.oursky.dev and seed node 2.

**Comment by hochiw** [comment] 2022-03-30 10:24
updated

**Comment by rickmak** [comment] 2022-03-31 07:06
Few comments, 

`likecoin-public-testnet-4.oursky.dev` is `node-vm-testnet-node1`. They should be combined.
The content of testnet and the history should include in the doc only if it relevance to the operation now. If it is not relevance, content should be remove, they will be in git history anyway.

The root README should be maintained as index.

**Closed** 2022-04-07 07:26 UTC
